# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

os: 
  - osx
  - linux


# Packages to install from specific sources other than CRAN   
use_bioc: true
bioc_required: true
bioc_packages:
  - phyloseq
  
# Linus System dependencies:
apt_packages:
  - libgsl0-dev
  
# Increase build time-out time - because of long package vignette built times

script:
  - |
    R CMD build .
    travis_wait 20 R CMD check stray.tar.gz
    
after_failure:
  find *Rcheck -name '*.fail' -print -exec cat '{}' \;